#!/usr/bin/env python
import os
import sys

if 3 != len(sys.argv):
    print "Usage:", sys.argv[0], "encFsDir mountDir"
    sys.exit(1)
absolutes = map(os.path.abspath, sys.argv)
sys.exit(
    os.system(
        '/usr/bin/encfs -o allow_root "' +
        absolutes[1] + '" "' +
        absolutes[2] + '"'))
