#!/bin/bash
#
# Whenever I want to find something in a folder hierarchy,
# but only for a specific type of files... e.g.:
#
#    findIn .py '^def.*order'
#
EXTENSION=$(echo "$1" | sed 's/\./\\./g')
shift
# If output goes to a tty, don't wrap around
if [ -t 1 ] ; then
    [ -z "$COLUMNS" ] && COLUMNS=$(tput cols)
    CUT_CMD="cut -c1-$COLUMNS"
else
    CUT_CMD="cat"
fi
find . -type f -iname '*'${EXTENSION} -exec grep -i --color=auto "$@" '{}' /dev/null \; 2>/dev/null | $CUT_CMD
#sag -G ".*${EXTENSION}" "$@"
