#!/bin/bash
#
# Whenever I want to find something in a folder hierarchy,
# but only for a specific type of files... e.g.:
#
#    findIn .py '^def.*order'
#
EXTENSION=$(echo "$1" | sed 's/\./\\./g')
shift
#find . -type f -iname '*'${EXTENSION} -exec grep --color=auto "$@" '{}' /dev/null \;
sag -G ".*${EXTENSION}" "$@"
