#!/bin/bash
#
# Whenever I want to find something in a folder hierarchy,
# but only for a specific type of files...
#
# e.g.:
#
#    findIn .py '^def.*order'
#
# or
#
#    findIn '.[ch]' '^void'
#
# To make a case-insensitive search, pass "-i" in front (before the extension)

if [ "$1" == "-i" ] ; then
    CASE="-i"
    shift
else
    CASE=""
fi

EXTENSION="$(echo "$1" | sed 's/\./\\./g')"
shift

# If output goes to a tty, I don't want a wrap around, but I do want colors
if [ -t 1 ] ; then
    COLORS="always"
    tput rmam  # Stop wrapping
else
    COLORS="none"
fi
find . -type f -iname '*'"${EXTENSION}" -exec grep ${CASE} --color="$COLORS" -- "$@" '{}' /dev/null \; 2>/dev/null
if [ -t 1 ] ; then
    tput smam  # Reset wrapping
fi
#sag -G ".*${EXTENSION}" "$@"
