#!/bin/sh
#
# Used for nice diff output from 'git diff' 
# For details look up my ~/.vimrc in GitHub
# (http://github.com/ttsiodras/dotvim.git/.vimrc) 
# and read the related comments (search for gitconfig).
#
MELD=$(which meld)
if [ ! -x "$MELD" ] ; then
    MELD=vimdiff
fi
if [ -z $SSH_CLIENT ] ; then
    $MELD "$2" "$5"
else
    vimdiff "$2" "$5"
fi
exit 0
