#!/bin/bash
#
# Extract the .aac audio from files generated by youtube-dl
#
mkvmerge -o /dev/shm/temp.mkv -D "$1"
mkvextract tracks /dev/shm/temp.mkv 0:/dev/shm/temp.aac
rm -f /dev/shm/temp.mkv
echo Created /dev/shm/temp.aac
