#!/bin/sh
#
# A helper script to debug makefiles - from the best Makefile article
# I have ever read in my life:
#
#  https://web.archive.org/web/20180306001530/http://gromnitsky.users.sourceforge.net/articles/notes-for-new-make-users/
# 
unset TERMCAP
re_env=$(env | cut -d= -f1 | tr \\n '|')
re_dot_smthg='\.[^ ]+'
re_autovars='[%*+<?^@][^ ]'
re_misc='GNUMAKEFLAGS|MAKE([^ ]+)?|MFLAGS|SUFFIXES|-\*-command-variables-\*-'

make -rR -pk -q "$@" \
    | grep -vE "^(${re_env}#|$re_dot_smthg|$re_autovars|$re_misc) " \
    | cat -s
