#!/bin/bash
if [ `id -u` -ne 0 ] ; then
    echo As root
    exit 1
fi
echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo ondemand > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
cat /sys/devices/system/cpu/cpu?/cpufreq/scaling_governor
