#!/bin/bash
if [ `id -u` -ne 0 ] ; then
    echo As root
    exit 1
fi
for i in /sys/devices/system/cpu/cpu?/cpufreq/scaling_governor ; do
    echo performance > $i
done
cat /sys/devices/system/cpu/cpu?/cpufreq/scaling_governor
echo 0 > /proc/sys/kernel/randomize_va_space
