#!/bin/bash
if [ `id -u` -ne 0 ] ; then
    echo As root
    exit 1
fi
echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo performance > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
cat /sys/devices/system/cpu/cpu?/cpufreq/scaling_governor
echo 0 > /proc/sys/kernel/randomize_va_space
