#!/bin/sh
#
# Fastest, hassle-free transfer of files:
# On the receiving end, run this script.
# On the sending end, run 'SendAtWarp9r'.
#
if [ $# -lt 1 ] ; then
	echo Usage: ReceiveAtWarp9r hostSendingTheData
	exit 0;
fi
HOST="$1"
shift
nc -w 2 "$HOST" 9656 | lzop -d | tar xpvf -
