#!/bin/bash
#
# Fastest, hassle-free transfer of files:
# On the receiving end, run 'ReceiveAtWarp9'.
# On the sending end, run this script.
#
if [ $# -lt 2 ] ; then
	echo Usage: SendAtWarp9 host filesAndOrFolders
	exit 0;
fi
HOST="$1"
shift
tar cf - "$@" | lzop -c -1 | nc -w 2 $HOST 9656
