# set -g mode-mouse on
# set -g mouse-resize-pane on
# set -g mouse-select-pane on
# set -g mouse-select-window on

# Otherwise, visual select no longer works inside VIM
#set -g default-terminal "xterm"

# Change status bar color
set -g status-bg brightblue

# VIM bindings to navigate panes
bind j select-pane -D
bind k select-pane -U
bind h select-pane -L
bind l select-pane -R

# Easy mnemonics for spliting with '|' and '-'
bind | split-window -h
bind - split-window -v

# VIM bindings to resize panes
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5

set -g display-panes-time 5000 # C-b q

# navigate while copy/pasting
setw -g mode-keys vi

# The ESC-j fiasco in Tmux
set -g escape-time 20

# C-c: save into system clipboard (+). With preselection.
bind C-c choose-buffer "run \"tmux save-buffer -b %% - | xclip -i -sel clipboard\" \; run \" tmux display \\\"Clipboard \(+\) filled with: $(tmux save-buffer -b %1 - | dd ibs=1 obs=1 status=noxfer count=80 2> /dev/null)... \\\" \" "
# C-v: copy from + clipboard.
bind C-v run "tmux set-buffer \"$(xclip -o -sel clipboard)\"; tmux paste-buffer" \; run "tmux display \"Copied from \(+\) $(xclip -o -sel clipboard | dd ibs=1 obs=1 status=noxfer count=80 2> /dev/null)... \""

# C-d: save into selection clipboard (*). With preselection.
bind C-d choose-buffer "run \"tmux save-buffer -b %% - | xclip -i\" \; run \" tmux display \\\"Clipboard \(*\) filled with: $(tmux save-buffer -b %1 - | dd ibs=1 obs=1 status=noxfer count=80 2> /dev/null)... \\\" \" "
# C-f: copy from * clipboard.
bind C-f run "tmux set-buffer \"$(xclip -o)\"; tmux paste-buffer" \; run "tmux display \"Copied from \(*\) $(xclip -o | dd ibs=1 obs=1 status=noxfer count=80 2> /dev/null)... \""

# Mirror screen's C-a C-a behavior (last window toggle) with C-b C-space. C-b C-b is used for nested tmux, so don't overwrite it.
bind-key C-Space last-window

run-shell ~/dotfiles/tmux-resurrect/resurrect.tmux

# Auto-completion from the tmux buffer contents
# using https://github.com/laktak/extrakto
# Just C-b TAB then select what you want, hit TAB

run-shell ~/GitHub/extrakto/extrakto.tmux

# disable sound bell
set -g bell-action none

# enable visual bell
set -g visual-bell on

# Large history 
set-option -g history-limit 10000

# Kitty
set -g extended-keys on
